export const LOCATIONS = [
  { name: 'Abiy Addi', code: 'ABYADD' },
  { name: 'Abomsa', code: 'ABOMSA' },
  { name: 'Adama', code: 'ADAMA' },
  { name: 'Addis Alem', code: 'ADDLEM' },
  { name: 'Addis Zemen', code: 'ADDZEM' },
  { name: 'Adet', code: 'ADET' },
  { name: 'Adigrat', code: 'ADIGRA' },
  { name: 'Adwa', code: 'ADWA' },
  { name: 'Agaro', code: 'AGARO' },
  { name: 'Akaki', code: 'AKAKI' },
  { name: 'Alaba Kulito', code: 'ALBKUL' },
  { name: 'Amba Mariam', code: 'AMBAMA' },
  { name: 'Ambo', code: 'AMBO' },
  { name: 'Angacha', code: 'ANGACH' },
  { name: 'Ankober', code: 'ANKOBE' },
  { name: 'Arboye', code: 'ARBOYE' },
  { name: 'Areka', code: 'AREKA' },
  { name: 'Asaita', code: 'ASAITA' },
  { name: 'Asella', code: 'ASELLA' },
  { name: 'Assosa', code: 'ASSOSA' },
  { name: 'Aware', code: 'AWARE' },
  { name: 'Awasa', code: 'AWASA' },
  { name: 'Awash', code: 'AWASH' },
  { name: 'Axum', code: 'AXUM' },
  { name: 'Azezo', code: 'AZEZO' },
  { name: 'Alamata', code: 'ALAMAT' },
  { name: 'Alem Ketema', code: 'ALEKET' },
  { name: 'Babille', code: 'BABILL' },
  { name: 'Badme', code: 'BADME' },
  { name: 'Bahir Dar', code: 'BAHDAR' },
  { name: 'Bati', code: 'BATI' },
  { name: 'Batu', code: 'BATU' },
  { name: 'Bedele', code: 'BEDELE' },
  { name: 'Bedessa', code: 'BEDESS' },
  { name: 'Beica', code: 'BEICA' },
  { name: 'Bekoji', code: 'BEKOJI' },
  { name: 'Bele', code: 'BELE' },
  { name: 'Bichena', code: 'BICHEN' },
  { name: 'Bishoftu', code: 'BISHOF' },
  { name: 'Bitena', code: 'BITENA' },
  { name: 'Boditi', code: 'BODITI' },
  { name: 'Bonga', code: 'BONGA' },
  { name: 'Butajira', code: 'BUTAJI' },
  { name: 'Chiro', code: 'CHIRO' },
  { name: 'Chencha', code: 'CHENCH' },
  { name: 'Dessie', code: 'DESSIE' },
  { name: 'Dabat', code: 'DABAT' },
  { name: 'Dangila', code: 'DANGIL' },
  { name: 'Debarq', code: 'DEBARQ' },
  { name: 'Debre Marqos', code: 'DEBMAR' },
  { name: 'Debre Tabor', code: 'DEBTAB' },
  { name: 'Debre Werq', code: 'DEBWER' },
  { name: 'Debre Zebit', code: 'DEBZEB' },
  { name: 'Dejen', code: 'DEJEN' },
  { name: 'Delgi', code: 'DELGI' },
  { name: 'Dembecha', code: 'DEMBEC' },
  { name: 'Dembidolo', code: 'DEMBID' },
  { name: 'Dessie', code: 'DESSIE' },
  { name: 'Dila', code: 'DILA' },
  { name: 'Dimtu', code: 'DIMTU' },
  { name: 'Dire Dawa', code: 'DIREDW' },
  { name: 'Dodola', code: 'DODOLA' },
  { name: 'Dolo Odo', code: 'DOLODO' },
  { name: 'Durame', code: 'DURAME' },
  { name: 'Dalocha', code: 'DALOCH' },
  { name: 'Dukem', code: 'DUKEM' },
  { name: 'Danan', code: 'DANAN' },
  { name: 'Ejaji', code: 'EJAJI' },
  { name: 'Elidar', code: 'ELIDAR' },
  { name: "Finicha'a", code: 'FINCHA' },
  { name: 'Fiche', code: 'FICHE' },
  { name: 'Finote Selam', code: 'FINSEL' },
  { name: 'Freweyni', code: 'FREWEY' },
  { name: 'Gondar', code: 'GONDAR' },
  { name: 'Gambela', code: 'GAMBEL' },
  { name: 'Gesuba', code: 'GESUBA' },
  { name: 'Gelemso', code: 'GELEMS' },
  { name: 'Ghimbi', code: 'GHIMBI' },
  { name: 'Ginir', code: 'GINIR' },
  { name: 'Goba', code: 'GOBA' },
  { name: 'Gode', code: 'GODE' },
  { name: 'Gololcha', code: 'GOLOLC' },
  { name: 'Gore', code: 'GORE' },
  { name: 'Gorgora', code: 'GORGOR' },
  { name: 'Gununo', code: 'GUNUNO' },
  { name: 'Harar', code: 'HARAR' },
  { name: 'Hawassa', code: 'HAWASS' },
  { name: 'Hayq', code: 'HAYQ' },
  { name: 'Holeta', code: 'HOLETA' },
  { name: 'Hosaena', code: 'HOSAEN' },
  { name: 'Humera', code: 'HUMERA' },
  { name: 'Huruta', code: 'HURUTA' },
  { name: 'Imi', code: 'IMI' },
  { name: 'Jijiga', code: 'JIJIGA' },
  { name: 'Jimma', code: 'JIMMA' },
  { name: 'Jinka', code: 'JINKA' },
  { name: 'Kebri Mangest', code: 'KEBMAN' },
  { name: 'Kercheche', code: 'KERCHE' },
  { name: 'Kobo', code: 'KOBO' },
  { name: 'Kombolcha', code: 'KOMBOC' },
  { name: 'Konso', code: 'KONSO' },
  { name: 'Kulubi', code: 'KULUBI' },
  { name: 'Kurmuk', code: 'KURMUK' },
  { name: 'Lalibela', code: 'LALIBE' },
  { name: 'Limmu Inariya', code: 'LIMINA' },
  { name: 'Maji', code: 'MAJI' },
  { name: 'Maqora', code: 'MAQORA' },
  { name: 'Maychew', code: 'MAYCHE' },
  { name: "Mek'ele", code: 'MEKELE' },
  { name: 'Mersa', code: 'MERESA' },
  { name: 'Mandi', code: 'MANDI' },
  { name: 'Metemma', code: 'METEMM' },
  { name: 'Metu', code: 'METU' },
  { name: 'Mizan Teferi', code: 'MIZTEF' },
  { name: 'Mojo', code: 'MOJO' },
  { name: 'Mota', code: 'MOTA' },
  { name: 'Moyale', code: 'MOYALE' },
  { name: 'Negash', code: 'NEGASH' },
  { name: 'Negele Boran', code: 'NEGBOR' },
  { name: 'Nejo', code: 'NEJO' },
  { name: 'Nekemte', code: 'NEKEMT' },
  { name: 'Bale Robe', code: 'BALERO' },
  { name: 'Sawla', code: 'SAWLA' },
  { name: 'Seka', code: 'SEKA' },
  { name: 'Shashamane', code: 'SHASHA' },
  { name: 'Sheraro', code: 'SHERAR' },
  { name: 'Shire', code: 'SHIRE' },
  { name: 'Shilavo', code: 'SHILAV' },
  { name: 'Wolaita Sodo', code: 'WOLASO' },
  { name: 'Sodore', code: 'SODORE' },
  { name: 'Sekota', code: 'SEKOTA' },
  { name: 'Semera', code: 'SEMERA' },
  { name: 'Tebela', code: 'TEBELA' },
  { name: 'Tenta', code: 'TENTA' },
  { name: 'Teppi', code: 'TEPPI' },
  { name: 'Tiya', code: 'TIYA' },
  { name: 'Tullu Milki', code: 'TULMIL' },
  { name: 'Turmi', code: 'TURMI' },
  { name: 'Wacca', code: 'WACCA' },
  { name: 'Waliso', code: 'WALISO' },
  { name: 'Walwal', code: 'WALWAL' },
  { name: 'Werder', code: 'WERDER' },
  { name: 'Wereta', code: 'WERETA' },
  { name: 'Woldia', code: 'WOLDIA' },
  { name: 'Wolleka', code: 'WOLLEK' },
  { name: 'Worabe', code: 'WORABE' },
  { name: 'Wuchale', code: 'WUCHAL' },
  { name: 'Wukro', code: 'WUKRO' },
  { name: 'Yabelo', code: 'YABELO' },
  { name: 'Yeha', code: 'YEHA' },
  { name: 'Yirga Alem', code: 'YIRALE' },
];
